name: Build

on:
  pull_request:
  push:
    branches: 
      - master
jobs:
  test:
    name: Run Builds
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: npm build
      run: npm run build